#!/bin/bash
set -e
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# shellcheck source=./common.sh
source "${DIR}/common.sh"

cd "$DIR"
./lambda-build

aws lambda update-function-code \
    --function-name "$(tf_output lambda_function_name)" \
    --zip-file "fileb://$artifacts_dir/lambda.zip"
