#!/bin/bash
set -e
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$DIR"

cd "../deployment"
aws sns publish \
    --topic-arn "$(terraform output --raw input_sns_topic_arn)" \
    --message "$1"
